Repository RezaRahemtola/Area, pull requests merged in 2023-10, with the labels that each got.

#77 Supervisor CI
  .github/workflows/main.yml
Labels: enhancement, patch

#126 Updated service images in database to unify the file format for the frontend (hello @Tomi-Tom)
  backend/back/src/database.ts
  backend/back/src/services/seed/1698161840408-UpdateServiceImagesToBrandFetchSVGs.ts
Labels: bug, enhancement, chore, patch

#129 GitHub on push webhook action
  backend/back/src/app.module.ts
  backend/back/src/connections/connections.controller.ts
  backend/back/src/connections/connections.service.ts
  backend/back/src/connections/oauth.service.ts
  backend/back/src/database.ts
  backend/back/src/grpc/grpc.controller.ts
  backend/back/src/grpc/grpc.service.ts
  backend/back/src/types/jobIds.ts
  backend/back/src/types/jobParams.ts
  backend/back/src/types/jobs.ts
  backend/back/src/webhooks/services/gihub-webhook.service.ts
  backend/back/src/webhooks/webhooks.controller.ts
  backend/back/src/webhooks/webhooks.module.ts
  backend/back/src/workflows/seed/1698179108023-CreateGithubOnIssueCreationArea.ts
  backend/back/yarn.lock
  backend/supervisor/docker-compose.yml
  backend/supervisor/jobs/images.go
  backend/supervisor/jobs/jobs.go
  backend/workers/github/Dockerfile
  backend/workers/github/package.json
  backend/workers/github/src/issues/create.ts
  backend/workers/github/src/main.ts
  backend/workers/github/src/util/params.ts
  backend/workers/github/src/webhooks/setup.ts
  backend/workers/github/yarn.lock
Labels: enhancement

#130 fix: prod crashes with areas
  backend/back/src/workflows/workflows.service.ts
  backend/back/yarn.lock
  backend/supervisor/jobs/jobs.go
  backend/workers/github/.dockerignore
Labels: bug

#138 Fixed bug when updating a workflow with the same name
  backend/back/src/workflows/workflows.service.ts
Labels: bug, patch

#139 Added documentation for the /about.json endpoint
  backend/back/src/about/about.controller.ts
Labels: documentation, patch

#131 YouTube new video action
  backend/back/package.json
  backend/back/src/database.ts
  backend/back/src/jobs/jobs.service.ts
  backend/back/src/types/jobIds.ts
  backend/back/src/types/jobParams.ts
  backend/back/src/types/jobs.ts
  backend/back/src/workflows/seed/1698251712512-CreateGoogleOnNewVideo.ts
  backend/back/yarn.lock
  backend/supervisor/jobs/images.go
  backend/workers/google/.gitignore
  backend/workers/google/main.py
  backend/workers/google/poetry.lock
  backend/workers/google/pyproject.toml
  backend/workers/google/src/youtube/on_video.py
Labels: enhancement

#136 Excluded webhook endpoints
  backend/back/src/webhooks/webhooks.controller.ts
Labels: documentation, patch

#145 Github Commit & Pull Request Actions
  backend/back/src/database.ts
  backend/back/src/types/jobIds.ts
  backend/back/src/types/jobs.ts
  backend/back/src/webhooks/services/gihub-webhook.service.ts
  backend/back/src/workflows/seed/1698353438280-CreateGithubCommitPRAreas.ts
  backend/supervisor/jobs/images.go
Labels: enhancement

#153 Fixed user update bug and some logic
  backend/back/src/users/users.service.ts
Labels: bug, patch

#154 Fixed workflow update
  backend/back/src/workflows/workflows.service.ts
Labels: bug, patch

#150 Backend: Job magic params
  backend/back/src/database.ts
  backend/back/src/jobs/jobs.service.ts
  backend/back/src/migrations/1698521602687-WorkflowAreaReturnParams.ts
  backend/back/src/services/entities/area.entity.ts
  backend/back/src/types/jobIds.ts
  backend/back/src/webhooks/services/gihub-webhook.service.ts
  backend/workers/google/src/docs/create_document.py
  backend/workers/google/src/youtube/on_video.py
Labels: enhancement

#156 Backend: Linear first AREAs
  backend/back/src/database.ts
  backend/back/src/services/dto/area.dto.ts
  backend/back/src/types/jobIds.ts
  backend/back/src/types/jobParams.ts
  backend/back/src/types/jobs.ts
  backend/back/src/webhooks/services/linear-webhook.service.ts
  backend/back/src/webhooks/webhooks.controller.ts
  backend/back/src/webhooks/webhooks.module.ts
  backend/back/src/workflows/seed/1698614949784-CreateLinearCreateIssueAreas.ts
  backend/supervisor/docker-compose.yml
  backend/supervisor/jobs/images.go
  backend/supervisor/jobs/jobs.go
  backend/workers/linear/.dockerignore
  backend/workers/linear/.eslintrc.yaml
  backend/workers/linear/.gitignore
  backend/workers/linear/.prettierrc.yaml
  backend/workers/linear/Dockerfile
  backend/workers/linear/package.json
  backend/workers/linear/src/issues/create.ts
  backend/workers/linear/src/main.ts
  backend/workers/linear/src/util/grpc.ts
  backend/workers/linear/src/util/params.ts
  backend/workers/linear/src/util/types.ts
  backend/workers/linear/tsconfig.json
  backend/workers/linear/yarn.lock
Labels: enhancement

#157 Mobile library popup
  frontend/mobile/lib/components/library/workflow_tile.dart
  frontend/mobile/lib/locales/app_en.arb
  frontend/mobile/lib/locales/app_fr.arb
  frontend/mobile/lib/locales/app_is.arb
Labels: enhancement, minor

#162 Fixed workflow update bug, was not saving reactions correctly
  backend/back/src/workflows/workflows.service.ts
Labels: bug, patch

#163 Fix misc things on back
  backend/workers/gitlab/.gitignore
  backend/workers/gitlab/src/webhooks/setup.py
  backend/workers/google/.gitignore
Labels: enhancement
