Repository RezaRahemtola/Area, pull requests merged in 2023-11, with the labels that each got.

#168 Backend: Miro Create a board Reaction
  backend/back/src/database.ts
  backend/back/src/types/jobIds.ts
  backend/back/src/types/jobParams.ts
  backend/back/src/types/jobs.ts
  backend/back/src/workflows/seed/1698793446046-CreateMiroCreateBoardReaction.ts
  backend/supervisor/docker-compose.yml
  backend/supervisor/jobs/images.go
  backend/workers/miro/.dockerignore
  backend/workers/miro/.gitignore
  backend/workers/miro/Dockerfile
  backend/workers/miro/main.py
  backend/workers/miro/poetry.lock
  backend/workers/miro/pyproject.toml
  backend/workers/miro/src/board/create.py
  backend/workers/miro/src/utils/parsing.py
Labels: enhancement

#169 Fixed some bugs in workflows functions
  backend/back/src/workflows/workflows.module.ts
  backend/back/src/workflows/workflows.service.ts
Labels: bug, patch

#175 LinkedIn service: I want to break free
  backend/back/src/connections/oauth.service.ts
Labels: bug, patch

#176 Fixed broken job launch
  backend/back/src/jobs/jobs.service.ts
  backend/back/src/workflows/workflows.controller.ts
  backend/back/src/workflows/workflows.service.ts
Labels: bug, patch

#189 Fix riot missing service in class validator
  backend/back/src/services/services.service.ts
Labels: bug

#190 Fix OAuth factory for Riot service
  backend/back/src/connections/oauth.service.ts
  backend/workers/riot/src/util/types.ts
Labels: bug

#192 Backend: Fixed reactions not properly handled by the back
  backend/workers/github/src/issues/close.ts
  backend/workers/github/src/issues/create.ts
  backend/workers/github/src/issues/reopen.ts
  backend/workers/linear/src/issues/create.ts
Labels: bug, patch

#191 Backend: Todoist reaction - Create a task
  backend/back/src/database.ts
  backend/back/src/types/jobIds.ts
  backend/back/src/types/jobParams.ts
  backend/back/src/types/jobs.ts
  backend/back/src/workflows/seed/1699101589099-CreateTodoistCreateTaskReaction.ts
  backend/supervisor/docker-compose.yml
  backend/supervisor/jobs/images.go
  backend/workers/todoist/.dockerignore
  backend/workers/todoist/.eslintrc.yaml
  backend/workers/todoist/.gitignore
  backend/workers/todoist/.prettierrc.yaml
  backend/workers/todoist/Dockerfile
  backend/workers/todoist/package.json
  backend/workers/todoist/src/main.ts
  backend/workers/todoist/src/tasks/create.ts
  backend/workers/todoist/src/util/grpc.ts
  backend/workers/todoist/src/util/params.ts
  backend/workers/todoist/tsconfig.json
  backend/workers/todoist/yarn.lock
Labels: enhancement, minor

#193 Backend: Airtable first reaction: delete a record
  backend/back/1699107944021-CreateAirtableDeleteRecordReaction.ts
  backend/back/src/database.ts
  backend/back/src/types/jobIds.ts
  backend/back/src/types/jobParams.ts
  backend/back/src/types/jobs.ts
  backend/supervisor/docker-compose.yml
  backend/supervisor/jobs/images.go
  backend/workers/airtable/.dockerignore
  backend/workers/airtable/.eslintrc.yaml
  backend/workers/airtable/.gitignore
  backend/workers/airtable/.prettierrc.yaml
  backend/workers/airtable/Dockerfile
  backend/workers/airtable/package.json
  backend/workers/airtable/src/main.ts
  backend/workers/airtable/src/record/delete.ts
  backend/workers/airtable/src/util/grpc.ts
  backend/workers/airtable/src/util/params.ts
  backend/workers/airtable/tsconfig.json
  backend/workers/airtable/yarn.lock
Labels: enhancement

#195 Fixed bug that was denying oauth users to update their settings and forbid them to change email
  backend/back/src/users/users.service.ts
Labels: bug, patch

#196 Backend: Twitter first reaction: post a tweet
  backend/back/1699107944021-CreateAirtableDeleteRecordReaction.ts
  backend/back/src/database.ts
  backend/back/src/types/jobIds.ts
  backend/back/src/types/jobParams.ts
  backend/back/src/types/jobs.ts
  backend/back/src/workflows/seed/1699107944021-CreateAirtableDeleteRecordReaction.ts
  backend/back/src/workflows/seed/1699115775099-CreateTwitterCreateTweetReaction.ts
  backend/supervisor/docker-compose.yml
  backend/supervisor/jobs/images.go
  backend/workers/twitter/.dockerignore
  backend/workers/twitter/.eslintrc.yaml
  backend/workers/twitter/.gitignore
  backend/workers/twitter/.prettierrc.yaml
  backend/workers/twitter/Dockerfile
  backend/workers/twitter/package.json
  backend/workers/twitter/src/main.ts
  backend/workers/twitter/src/tweet/create.ts
  backend/workers/twitter/src/util/grpc.ts
  backend/workers/twitter/src/util/params.ts
  backend/workers/twitter/src/util/types.ts
  backend/workers/twitter/tsconfig.json
  backend/workers/twitter/yarn.lock
  scripts/copy_proto.sh
Labels: enhancement, minor

#197 Backend: Riot icon to SVG
  backend/back/src/database.ts
  backend/back/src/services/seed/1699116526789-ChangeRiotLogoToSvg.ts
Labels: enhancement, patch

#200 Fixed user update bug when passing email
  backend/back/src/users/users.service.ts
Labels: bug, patch

#203 Backend Slack first reaction: create a message
  backend/back/src/database.ts
  backend/back/src/types/jobIds.ts
  backend/back/src/types/jobParams.ts
  backend/back/src/types/jobs.ts
  backend/back/src/workflows/seed/1699131357051-CreateSlackCreateMessageReaction.ts
  backend/supervisor/docker-compose.yml
  backend/supervisor/jobs/images.go
  backend/workers/slack/.dockerignore
  backend/workers/slack/.gitignore
  backend/workers/slack/Dockerfile
  backend/workers/slack/main.py
  backend/workers/slack/poetry.lock
  backend/workers/slack/pyproject.toml
  backend/workers/slack/src/message/create_message.py
  backend/workers/slack/src/utils/parsing.py
Labels: enhancement

#204 Factorization of job and jobs params typings
  backend/back/src/grpc/grpc.service.ts
  backend/back/src/jobs/jobs.service.ts
  backend/back/src/types/jobIds.ts
  backend/back/src/types/jobs.ts
Labels: bug, patch

#211 Duplicate web workflow
  frontend/web/components/FontAwesomeIcon.tsx
  frontend/web/components/library/LibraryWorkflowLine.tsx
  frontend/web/locales/en-US.ts
  frontend/web/locales/fr-FR.ts
  frontend/web/locales/is-IS.ts
  frontend/web/utils/workflows.ts
Labels: enhancement, minor

#210 Duplicate mobile workflow
  frontend/mobile/lib/components/library/workflow_tile.dart
  frontend/mobile/lib/locales/app_en.arb
  frontend/mobile/lib/locales/app_fr.arb
  frontend/mobile/lib/locales/app_is.arb
  frontend/mobile/lib/pages/landing.dart
  frontend/mobile/lib/pages/library.dart
  frontend/mobile/lib/utils/workflows.dart
Labels: enhancement, minor

#216 fix(back): AREAs QA
  backend/back/src/database.ts
  backend/back/src/grpc/grpc.service.ts
  backend/back/src/jobs/jobs.service.ts
  backend/back/src/workflows/seed/1699190007820-FixAddScopeToLinearOnIssueCreate.ts
  backend/supervisor/jobs/images.go
  backend/workers/linear/src/issues/create.ts
  backend/workers/todoist/src/tasks/delete.ts
Labels: enhancement

#227 hotfix: linear-create-comment
  backend/back/src/types/jobParams.ts
Labels: bug

#229 Web dashboard
  frontend/web/app/dashboard/page.tsx
  frontend/web/locales/en-US.ts
  frontend/web/locales/fr-FR.ts
  frontend/web/locales/is-IS.ts
  frontend/web/services/user/index.ts
  frontend/web/services/user/me.ts
Labels: enhancement, minor
